### ISSUE TITLE
jpivc.jar missing for command line usage

### ISSUE THREAD

**Issue by rfechtner** [eguvep/jpiv#3]
According to the [documentation](https://eguvep.github.io/jpiv/scripting.html) there is an option to process files from the command line e.g.:

> Some people prefer jpiv to accept a list of images on the command line. The images should be evaluated immediately. The executable jpivc.jar can do that. Launch a PIV evaluation via command line by executing `java -jar -Xmx4G jpivc.jar *.tiff`, for example. The files *.tiff are your PIV images.

However I can't find the suggested file jpivc.jar anywhere. 
Further when using the command line, how would I set settings like "General > consecutive" or "Interrogation Window" parameters

Cheers

**Comment by eguvep** [comment]
Dear Ron,
People rather use the following script now, instead of using the command line:
https://github.com/eguvep/jpiv/blob/master/jpiv/jpivlib/jsc/process_directories.jsc
However, I attached the java source code for  the command line wrapper.
[jpivc.txt](https://github.com/eguvep/jpiv/files/6907816/jpivc.txt)
Hope, this helps!
Regards!
Peter

**Comment by eguvep** [comment]
You may use Eclipse to compile it. If you do so, add the regular jpiv.jar as a library:
Project → Java Build Path → Libraries
Finally compile the jpivc project and export as a jar archive.
With this wrapper as a base, you can use all jpiv classes and methods like a tool-box and build your own terminal application. You can also modify the settings. The settings are just an object holding the parameters. They are all public, so you can directly read and write them:
https://github.com/eguvep/jpiv/blob/master/src/jpiv2/Settings.java

**Comment by eguvep** [comment]
@rfechtner, you can now launch the normal JPIV version also with command line options like `java -jar JPIV.jar -img *.tif`. Use `java -jar JPIV.jar -help` to see all options.

**Comment by rfechtner** [comment]
Awesome, thank you!
