### ISSUE TITLE
scripts and crop errors 

### ISSUE THREAD

**Issue by BaShGTH** [eguvep/jpiv#5]
Hi there, 

It's my first day using JPIV and somehow manged to break it :')

I've tried a few datasets of mine and the same synt0-4 sequence, both with some reasonable results, until I've came accross two issues:

(1) Exception in thread "Thread-5" java.lang.IllegalArgumentException: Crop The rectangular crop area must not be outside the image.
[crop.txt](https://github.com/eguvep/jpiv/files/9310737/crop.txt)

which I'm not entirely sure what it indicates since the same parameters worked fine before. So decided to start fresh and try synt dataset which led me to error (2)
(2) the scripts are gone from their menu- which even when the path is adjusted form 'preference -> path' still doesn’t fix it. So i tried running one from 'scripts->open' which basically resulted in nothing.
[synt 2d data gen.txt](https://github.com/eguvep/jpiv/files/9310739/synt.2d.data.gen.txt)

Would really appreciate all the help I can get.
Kind regards.

**Comment by eguvep** [comment]
Hi,
(1) Did you try to deselect ROI (region of interest) on »Settings - PIV - Interrogation Window«, just to see, if this is the error source? If yes, try to use different parameters. Remind that the coordinate origin is in the top left corner of the image. Positive x values increase to the left, positive y values increase downwards.
(2) The script that you have chosen manually, also relies on some external binaries in the script directory. After setting the path, you need to restart JPIV. The content of the file is just read on startup, when the drop down menu items are generated.
I hope, this helps!
Success!
Peter

**Comment by BaShGTH** [comment]
Hi Peter! Many thanks for the prompt reply and suggestions! 

It worked, removing the ORI solved the probelm and I was using JPIVlib/jsc for the path and using only JPIVlib fixed it... now on to work out the actual anaylysis :)

Bana

**Comment by eguvep** [comment]
Thanks for the feedback – have a nice weekend!
