### ISSUE TITLE
using more than 2 cores to speed up image processing

### ISSUE THREAD

**Issue by newedb** [eguvep/jpiv#6]
Just downloaded the software a few minutes ago. When I tried it to process 4 thousand images, I noticed it is only using 2 out of 16 available cores.

Is it possible to use all 16 cores?
In addition, how can I run two separate java instances to process two different sets of images?

Thanks.

**Comment by eguvep** [comment]
Each image is cut in parts and then the parts are processed on different cores. Finally, the results are stitched together again. This process does not scale too well with the number of cores. Based on experience and testing, the number of cores is calculated based on the size of the image. Check the following line in the code:
https://github.com/eguvep/jpiv/blob/aefd92947fc351bfcd13121a3db200a7c78ec5f2/src/jpiv2/PivEvaluation.java#L120
If you process larger images, the number of used cores will be higher. The number of cores does not scale with the number of processed images! You may change the code of course, to do so.
But you may start multiple processes! Just adjust the parameters and start the first process. The first JPIV instance will now read the settings and will process your images. You can then fire up a second instance of JPIV (you may use the terminal for that). Change the settings and start the second process. The first process will not care about the altered settings while the first process is still running, but may take over the new settings of the second process after finishing the first job. We regularly run multiple processes in parallel on a cluster computer. This makes JPIV (in our use case) much (!) faster than a commercial programme (that would need a licence for each instance), although the JAI-FFT, that JPIV is using, is not very efficient (and much slower than the commercial alternative we are using here).
